### ISSUE TITLE
TRAIN.BATCH_SIZE_SOURCE  and BATCH_SIZE_TARGET

### ISSUE THREAD

**Issue by InstantWindy** [valeoai/ADVENT#10]
Hi. What the values of TRAIN.BATCH_SIZE_SOURCE  and BATCH_SIZE_TARGET? They must be 1? Thanks.

**Comment by tuanhungvu** [comment]
Hello @InstantWindy , those batch sizes depend on the image resolutions and the GPU memory. You can modify them as you wish. In our experiments, we used batch sizes of 1.
T-H
