### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by InstantWindy** [valeoai/ADVENT#11]
Hi. I git clone your repro and run “python train.py --cfg ./configs/advent.yml”, but I test it with the command "python test.py --cfg ./configs/advent.yml" , the test mIoU is only 43.25 which is lower than the paper. Did you finetune the model  and get mIoU 43.8? Thanks.

**Comment by tuanhungvu** [comment]
Hello @InstantWindy , please have a look at #6 
T-H
