### ISSUE TITLE
Could you release the code related to detection DA?

### ISSUE THREAD

**Issue by dlsrbgg33** [valeoai/ADVENT#14]
Hi, 
Thank you for your great work and contribution.
As a title, could you release the SSD code with your DA approach?
Thank you.

**Comment by tuanhungvu** [comment]
Hello @dlsrbgg33 , sorry for the late replay. Thanks for your interest in our work.
Currently we don't have a concrete plan to release the detection part, mainly due to our lack of time. FYI, the detection part is built upon this repo https://github.com/amdegroot/ssd.pytorch .
Best,
T-H

**Comment by andgitchang** [comment]
@tuanhungvu 
I would like to know the advent detection used (1) only the classification header of SSD to calculate entropy maps or (2) both classification and regression headers to adapt?
It seems that the classification header for entropy maps is more reasonable, said 80 classes of COCO, where 4 classes bounding box (xyxy) of the regression header calculating entropy maps is a bit of weird.
Thanks in advance.
