### ISSUE TITLE
How do  you choose the 'early stoping' parameter ?

### ISSUE THREAD

**Issue by idealwei** [valeoai/ADVENT#3]
Hi, I am very curious that how you choose the "early stoping" parameter. And it's well known that adv training is not stable, so how you choose your best segmentation model?

**Comment by tuanhungvu** [comment]
Hi @idealwei, regarding early stopping, we followed the one used in [AdaptSegNet](https://github.com/wasidennis/AdaptSegNet). To get the best model, we evaluate intermediate snapshots and keep the best one.
