### ISSUE TITLE
About the code of ADVENT

### ISSUE THREAD

**Issue by Solacex** [valeoai/ADVENT#6]
Hello, 

I am trying to reproduce the result reported in the paper( ADVENT) but the result I got is 42.36(advent only, best result), I want to know if there is any mistake in the configure or have you ever meet such result?
![image](https://user-images.githubusercontent.com/12868455/65240152-eee78780-db23-11e9-844c-fb1e54f4f099.png)

**Comment by tuanhungvu** [comment]
Hello @Solacex , as adversarial training is not stable, you may have to train a few times to reach the comparable performance. In our experiments, we observed performance ranging from 43.3-44.1% . Please refer to https://github.com/valeoai/ADVENT#training for more of our experiment details.
T-H
