### ISSUE TITLE
About implementation of AdvEnt+MinEnt

### ISSUE THREAD

**Issue by changliu816** [valeoai/ADVENT#7]
Hi,

I implemented the AdvEnt+MinEnt (45.5 in paper) by combining advEnd and MinEnd together, but got 42.48 % instead.

For GTA5-> Cityscapes:
I saw the result for MinEnt + ER in paper. My question is that do you use +ER or class prior techniques with AdvEnd+MinEnt experiment ?

Could you please briefly clarify how you implement AdvEnd+MinEnt experiment ?

Best,
Chang

**Comment by tuanhungvu** [comment]
Hello @changliu816, we have not jointly trained AdvEnt + MinEnt in the paper (still you can try). The reported number is of the ensemble of the two models (see Section 4.2). To your second question, the MinEnt model used in this ensemble was (MinEnt + ER) in Table 1.
Best,
T-H
