### ISSUE TITLE
Question about caculation of image mean?

### ISSUE THREAD

**Issue by Balabala-Hong** [valeoai/ADVENT#8]
I found in your code `IMG_MEAN` is set to `[104.00698793, 116.66876762, 122.67891434]`, is `IMG_MEAN` calcuated on source domain only or target domain only or both?

**Comment by tuanhungvu** [comment]
Hello @Lelouch-Ice , IMG_MEAN was computed from ImageNet. 
T-H

**Comment by soans1994** [comment]
@tuanhungvu 
hello authors,

i have some queries regarding your work, 

1. after mean transformation the image becomes darker. Is this correct?
2. why is the rgb image converted to bgr in the dataloader?

![Figure_2](https://user-images.githubusercontent.com/30766648/167597297-20aff169-9530-4353-9626-b9284c0fed26.png)
![Figure_1](https://user-images.githubusercontent.com/30766648/167597312-8252502c-59f3-40cb-9b96-c616ac5f31e5.png)

i used the dataloader as follows
```
dst = cityscapesDataSet(DATA_DIRECTORY, DATA_LIST_PATH, max_iters=NUM_STEPS * ITER_SIZE * BATCH_SIZE,
                    crop_size=INPUT_SIZE,
                    scale=True, mirror=True, mean=(104.00698793, 116.66876762, 122.67891434))
```
but when i check the mean of a tensor batch it shows 
`tensor([-41.5335, -43.1566, -60.2354])`

what am i missing please help
